#My Properties File
#Tue Apr 07 22:45:14 EDT 2026
BASE_URI=http\://64.227.160.186\:9000/v1
Env=qa
JAVA\ VERSION=21.0.8
OPERATING\ SYSTEM=Windows 10
OS\ VERSION=10.0
Project\ Name=API Automation Framework
